# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

services:
  - xvfb

before_install:
  - sudo apt-get update
  - sudo apt-get install -y meld
  # Fix GtkWarning: could not open display
  # <https://blog.matthieu.brouillard.fr/2013/09/19/headfull-vs-headless-travis-ci-build/>
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
