# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

services:
  - xvfb

before_install:
  - sudo apt-get update
  - sudo apt-get install -y meld
